export default {
    FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    CREATE_ENTITY_BEGIN: 'CREATE_ENTITY_BEGIN',
    CREATE_ENTITY_ERROR: 'CREATE_ENTITY_ERROR',
    CREATE_ENTITY_SUCCESS: 'CREATE_ENTITY_SUCCESS',
    DELETE_ENTITY_SUCCESS: 'DELETE_ENTITY_SUCCESS',
    DELETE_ENTITY_ERROR: 'DELETE_ENTITY_ERROR',
    UPDATE_INFO_BEGIN: 'UPDATE_INFO_BEGIN',
    UPDATE_INFO_SUCCESS: 'UPDATE_INFO_SUCCESS',
    UPDATE_INFO_ERROR: 'UPDATE_INFO_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR'
};
