export default {
    FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    CREATE_ENTITY_BEGIN: 'CREATE_ENTITY_BEGIN',
    CREATE_ENTITY_ERROR: 'CREATE_ENTITY_ERROR',
    CREATE_ENTITY_SUCCESS: 'CREATE_ENTITY_SUCCESS'
};
